### ISSUE TITLE
graphite-api_1.0.1-exoscale1400326939_amd64.deb broken on debian wheezy

### ISSUE THREAD

**Issue by mfournier** [brutasse/graphite-api#103]
The documentation suggests graphite-api can be installed on debian wheezy by using the package hosted at https://packagecloud.io/exoscale/community/debian/

9f9574e5 and 37d907b3 are needed for the package to install on this distro, but once this is sorted out, the initscript silently fails to start the service:

```
# /etc/init.d/graphite-api start
# echo  $?
0
```

And the reason is:
```
# /usr/share/python/graphite/bin/gunicorn
/usr/share/python/graphite/bin/python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by /usr/share/python/graphite/bin/python)
/usr/share/python/graphite/bin/python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/share/python/graphite/bin/python)
```

wheezy comes with:
```
ii  libc6:amd64                  2.13-38+deb7u6      amd64               Embedded GNU C Library: Shared libraries
```

It looks like the package for wheezy was built on debian testing or one of the more recent ubuntus.

Not a huge issue, as it's trivial to rebuild packages yourself, but it leaves debian wheezy users unable to get started as easily as http://graphite-api.readthedocs.org/en/latest/installation.html suggests.

Once you release 1.0.2, can you please make sure to rebuild the packages on the target platforms ? Thanks :-)

**Comment by brutasse** [comment]
Thanks for the report… The package was built on Ubuntu 14.04. I'll try to publish specific packages for debian and ubuntu next time I make a release :)

**Comment by chjohnst** [comment]
Hey Bruno,

I have RedHat src rpms if interested, I use them to deploy in my
environment.

-Chris

**Comment by brutasse** [comment]
There are now separate builds for debian and ubuntu, closing. https://github.com/brutasse/graphite-api/releases
