### ISSUE TITLE
/metrics/index.json only works for whisper?

### ISSUE THREAD

**Issue by Dieterbe** [brutasse/graphite-api#104]
whenever i query for `/metrics/index.json` i just get a http timeout.
i started looking into and stumbled upon 5a9afee1ad1bc40777aa4deef7238c3444e72cf3

it looks like the `/metrics/index.json` handler does something whisper specific. in my case i use the influxdb backend and should just query influx for the data.

**Comment by Dieterbe** [comment]
here's a patch to query elasticsearch,
but this is ugly, values hardcoded and doesn't use finder plugins.

```
diff --git a/graphite_api/app.py b/graphite_api/app.py
index 57da53a..d66d8b7 100644
--- a/graphite_api/app.py
+++ b/graphite_api/app.py
@@ -209,15 +209,18 @@ def metrics_expand():
 
 @app.route('/metrics/index.json', methods=methods)
 def metrics_index():
-    index = set()
-    if os.path.exists(app.searcher.index_path):
-        with open(app.searcher.index_path, 'r') as f:
-            index = set([line.strip() for line in f if line])
-        if not index:
-            recurse('*', index)
-    else:
-        recurse('*', index)
-    return jsonify(sorted(index), jsonp=RequestParams.get('jsonp', False))
+    from elasticsearch import Elasticsearch
+    es = Elasticsearch(['localhost:9200'])
+    body = {
+        "fields": [],
+        "query": {
+            "match_all": {
+            }
+        }
+    }
+    res = es.search(index="graphite_metrics2", size=10000000, body=body)
+    series = [hit['_id'] for hit in res['hits']['hits']]
+    return jsonify(sorted(series), jsonp=RequestParams.get('jsonp', False))
 
 
```

**Comment by Dieterbe** [comment]
similar, but for influxdb
```
diff --git a/graphite_api/app.py b/graphite_api/app.py
index 57da53a..9379803 100644
--- a/graphite_api/app.py
+++ b/graphite_api/app.py
@@ -209,15 +209,21 @@ def metrics_expand():
 
 @app.route('/metrics/index.json', methods=methods)
 def metrics_index():
-    index = set()
-    if os.path.exists(app.searcher.index_path):
-        with open(app.searcher.index_path, 'r') as f:
-            index = set([line.strip() for line in f if line])
-        if not index:
-            recurse('*', index)
-    else:
-        recurse('*', index)
-    return jsonify(sorted(index), jsonp=RequestParams.get('jsonp', False))
+    from influxdb import InfluxDBClient
+    host="host"
+    port=8086
+    user="graphite"
+    passw="graphite"
+    db="graphite"
+    ssl=False
+    client = InfluxDBClient(host, port, user, passw, db, ssl)
+    ret = client.query("list series")
+    # as long as influxdb doesn't have good safeguards against
+    # series with bad data in the metric names, we must filter out
+    # like so:
+    series = [serie[1] for serie in ret[0]['points']
+        if serie[1].encode('ascii', 'ignore') == serie[1]]
+    return jsonify(sorted(series), jsonp=RequestParams.get('jsonp', False))
 
 
 def prune_datapoints(series, max_datapoints, start, end):
```

**Comment by brutasse** [comment]
There's nothing whisper-specific. The call to `recurse()` is backend-agnostic:

https://github.com/brutasse/graphite-api/blob/4445c5294115cdbaf44f1dde25474297ce6dbc0b/graphite_api/app.py#L249-L257

You're getting a timeout probably because it takes a long time to get all metrics. The `/metrics/search` call uses the search index and should be faster. Can you give it a try?

**Comment by Dieterbe** [comment]
i see. how and when is the index being generated though?  do i need to run a cron that posts to /index ? couldn't find it in docs.
I have the search_index config option set to a file, but it looks like the file is not writeable, will fix that and let you know.  However I don't understand why you recommend the /search endpoint as opposed to /index, it looks like they both use the index in a similar way?

I'm not a big fan of the current /metrics/index.json implementation because of this argument:
listing all series and searching for series are different opperations, 
doing searches/findnodes calls on storage can be much slower than just getting a list of all metrics.
So I think to satisfy requests that just ask for all metrics, we should be able to leverage backend features that can return all series without doing more expensive searches.

We could do this by making an index()/list() function on the finder, and the default implementation would be the one that calls recurse(), keeping current behavior.
this way specific finders can override the function and use optimized calls, which could also be used to fill the index instead of the current more expensive recurse based mechanism.

**Comment by brutasse** [comment]
Yeah, you need to post to `/index` to generate the index. If it's too long and times out, you could call the codepath for that URL from a python shell.

The API call should be much faster once the index is generated. How long does the generation take for you? And once it's generated, how long does a GET take?

**Comment by Dieterbe** [comment]
```
root@6b60ad427f00:~# time curl -X POST http://localhost:8000/index
curl: (52) Empty reply from server

real	2m0.381s
user	0m0.004s
sys	0m0.006s
root@6b60ad427f00:~# 
```

**Comment by brutasse** [comment]
Can you try with a python shell then?

```
from graphite_api import app
app.build_index()
```

**Comment by Dieterbe** [comment]
hey bruno,
```
root@6f5b75504feb:~# python2
Python 2.7.8 (2.5.0+dfsg-2~ppa1+ubuntu14.04, Feb 11 2015, 21:44:50)
[PyPy 2.5.0 with GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> from graphite_api import app
{"path": "/etc/graphite-api.yaml", "event": "loading configuration"}
{"index_path": "/srv/graphite/index", "event": "reading index data"}
{"index_path": "/srv/graphite/index", "total_entries": 0, "duration": 6.389617919921875e-05, "event": "search index reloaded"}
{"timezone": "America/New_York", "event": "configured timezone"}
>>>> import time
>>>> time.time();app.build_index();time.time()
1427986158.118702
{"index_path": "/srv/graphite/index", "event": "reading index data"}
{"index_path": "/srv/graphite/index", "total_entries": 578533, "duration": 0.6708858013153076, "event": "search index reloaded"}
('{"success": true, "entries": 578533}', 200, {'Content-Type': 'application/json'})
1427987403.474736
>>>> 1427987403.474736 - 1427986158.118702
1245.356034040451
>>>> 1245.356034040451 / 60
20.755933900674183
```
--> 21 minutes

ater that `time curl http://localhost:8000/metrics/index.json >/dev/null` takes about 7 seconds, which is pretty good compared to with my patch which does it in 5 seconds. but now generating the index is a slow and inefficient process. it would also be annoying to have to wait so long before new metrics even show up in index.json

**Comment by brutasse** [comment]
Yeah… The approach in cyanite when you have lots of metrics is to use elasticsearch as an index, the index being updated by the metrics receiver (cyanite daemon) instead of graphite. But even with that ES index, `/metrics/index.json` doesn't take advantage of it.

**Comment by Dieterbe** [comment]
so why don't we just make index() a finder method that defaults to the current implementation, but can be overridden to leverage more appropriate backend features (such as an influxdb 'list series' or ES listing of all id's)?
