### ISSUE TITLE
graphite-api.yaml loading issue

### ISSUE THREAD

**Issue by shaanaxx** [brutasse/graphite-api#107]
I am new to python and trying to install graphite-api using mod-wsgi and apache. I see the below errors in my error.log. I am assuming it is unable to read the /etc/graphite-api.yaml . I changed permissions on the yaml file as well as the index to read/write by all users. I did not see anything in my apache logs and process graphite-api is running with the below errors.

```
$ps -ef | grep graphite
daemon   27149 27146  0 19:07 ?        00:00:00 (wsgi:graphite-api)          -k start
```

Error.log details :
```
 [error] path='/etc/graphite-api.yaml' event='loading configuration'
 [error] path='/etc/graphite-api.yaml' event='loading configuration'
 [error] path='/etc/graphite-api.yaml' event='loading configuration'
 [error] path='/etc/graphite-api.yaml' event='loading configuration'
 [error] index_path='/srv/graphite/index' event='reading index data'
 [error] index_path='/srv/graphite/index' duration=3.0994415283203125e-05 total_entries=0 event='search index reloaded'
```

I even tried placing it in a different folder and using export GRAPHITE_API_CONFIG=/home/graphite-api.yaml
 It still did not work.

**Comment by brutasse** [comment]
The `[error]` prefix comes from apache -- these are normal events to see when you run graphite-api.

It looks like you're in debug mode though. Normally you should see json-formatted lines. Apart from that, nothing to worry about. Are you having issues accessing the API?

**Comment by shaanaxx** [comment]
Thanks for the reply Brutasse. I am running it in debug mode hoping to get some insight into the errors. In my graphite-api.yaml, if I use the default graphite finder , and i hit /render?target=test, i see "GET /render?target=test HTTP/1.1" 200 2360 but if i replace it with cyanite finder, i get "GET /render?target=test HTTP/1.1" 500 291. Below is my graphite-api.yaml.

search_index: /srv/graphite/index
functions:
  - graphite_api.functions.SeriesFunctions
  - graphite_api.functions.PieFunctions
whisper:
  directories:
    - /srv/graphite/whisper
time_zone: UTC
carbon:
  hosts:
    - 127.0.0.1:7002
  timeout: 1
  retry_delay: 15
  carbon_prefix: carbon
  replication_factor: 1
cyanite:
  urls:
    - http://127.0.0.1:8089
finders:
  - cyanite.CyaniteFinder
allowed_origins:
  - \*

My cyanite stand alone jar is up and carbon is listening on 2003 and I can successfully insert data into my cassandra cluster. I also did pip install cyanite, and i can see it added /usr/local/lib/python2.7/site-packages/cyanite . Not sure why it wants to complain  about cyanite finder. Please suggest. Below is my cyanite.yaml


carbon:
  host: "0.0.0.0"
  port: 2003
  rollups:
    - "1s:1h"
    - "10s:14d"
    - "10m:30d"
http:
  host: "0.0.0.0"
  port: 8089
logging:
  level: debug
  console: true
  files:
    - "/var/tmp/cyanite.log"
store:
  cluster: 'c14.test.com'
  keyspace: 'metric'
  chan_size: 100000 # defaults to 10000
  batch_size: 500 # defaults to 500

index:
  use: "io.cyanite.es_path/es-rest"
  index: "my_paths" 
  url: "http://0.0.0.0:9200" 
  chan_size: 100000 # defaults to 1000
  batch_size: 1000 # defaults to 1000

**Comment by brutasse** [comment]
Can you update graphite-api to the latest master? It now provides more debugging information with HTTP 500 response.

**Comment by brutasse** [comment]
Closing this since it's been inactive for quite some time. Feel free to reopen if the problem persists with the latest release.
