### ISSUE TITLE
Error 500 with some combinations of params and functions  

### ISSUE THREAD

**Issue by cdgraff** [brutasse/graphite-api#108]
Hi, 

I'm using Graphite-api, with cyanite, and Grafana 2.0.1 as dashboard.

But when try to render one metric got an error 500, this be the commands I try to debug.

curl -X POST 'http://graphite-api:8888/render?target=sortByMinima(servers.lnxd704.cpu.total.*)&from=1429710422&until=1429711022&format=json&maxDataPoints=627' => Response 500

The same as previous just without sort:
curl -X POST 'http://graphite-api:8888/render?target=servers.lnxd704.cpu.total.*&from=1429709880&until=1429713380&format=json&maxDataPoints=627' => Response 200

With Sort but with range time:
curl -X POST 'http://graphite-api:8888/render?target=sortByMinima(servers.lnxd704.cpu.total.*)&from=-1hours&until=now&format=json&maxDataPoints=627' => Response 200

Some advice to debug en more details?

Thanks!

**Comment by brutasse** [comment]
Can you update to the latest master version? Full tracebacks are visible in the HTTP response in case of app errors. I'm not able to reproduce the issue with the parameters combination you provided.

**Comment by cout** [comment]
I _may_ be running into the same or a similar issue (one difference: I do not get success when using relative time in place of absolute time).  As above, a query for a series succeeds:

    curl -X POST 'http://graphite-host:8888/render?target=collectd.myhost.disk-sda.disk_octets.*&from=-1hours&until=now&format=json&maxDataPoints=5'
    [{"target": "collectd.myhost.disk-sda.disk_octets.read", "datapoints": [[1348.2675219027778, 1444335120], [1052.4445949305557, 1444335840], [5.688876972222221, 1444336560], [0.0, 1444337280], [null, 1444338000]]}, {"target": "collectd.myhostl.disk-sda.disk_octets.write", "datapoints": [[35349.41154551388, 1444335120], [26339.154876881945, 1444335840], [7189.422537173612, 1444336560], [6607.860523791667, 1444337280], [5954.739903064816, 1444338000]]}]

but a query for a function fails:

    curl -X POST 'http://graphite-host:8888/render?target=sortByMinima(collectd.myhost.disk-sda.disk_octets.*)&from=-1hours&until=now&format=json&maxDataPoints=1304'
    Traceback (most recent call last):
      File "/home/pbrannan/.local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/home/pbrannan/.local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/home/pbrannan/.local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/home/pbrannan/.local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/home/pbrannan/.local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/pbrannan/graphite-api/graphite_api/app.py", line 401, in render
        series_list = evaluateTarget(context, target, data_store)
      File "/home/pbrannan/graphite-api/graphite_api/app.py", line 496, in evaluateTarget
        result = evaluateTokens(requestContext, tokens, data_store)
      File "/home/pbrannan/graphite-api/graphite_api/app.py", line 506, in evaluateTokens
        return evaluateTokens(requestContext, tokens.expression, data_store)
      File "/home/pbrannan/graphite-api/graphite_api/app.py", line 520, in evaluateTokens
        ret = func(requestContext, *args, **kwargs)
    TypeError: sortByMinima() takes exactly 2 arguments (1 given)

As best I can tell, something is going awry with parsing of the function call; pathsFromTarget() is returning an empty list, so no paths are fetched and stored in data_store.  Later, in evaluateTokens(), the call token does not have any arguments.

Curiously, the sumSeries function does not give a failure, but also does not return any data points:

    curl -X POST 'http://graphite-host:8888/render?target=sumSeries(collectd.myhost.disk-sda.disk_octets.*)&from=-1hours&until=now&format=json&maxDataPoints=5'                          
    []%

**Comment by brutasse** [comment]
I'm unable to reproduce this issue with current cyanite (master) and graphite-api 1.1. There was *probably* an issue in cyanite which has been fixed more or less recently. Please reopen the issue if the problem persists with new versions :)

**Comment by cout** [comment]
I believe I have found the cause of the above exception; it was caused by using an old version of pyparsing (1.5.2).  I upgraded by accident when I installed graphite-web (which has 1.5.7 explicitly in its requirements.txt); the exception no longer occurs.  I have confirmed that downgrading to 1.5.2 causes the exception to reappear.

Perhaps graphite-api should also pin pyparsing to 1.5.7?

**Comment by brutasse** [comment]
@cout thank you for the investigation! I've updated the dependency to specify `>=1.5.7`.
