### ISSUE TITLE
nonNegativeDerivate behaves differently in graphite-api and graphite-web

### ISSUE THREAD

**Issue by tilogaat** [brutasse/graphite-api#115]
Hi,

We are currently in the process of porting our internal dashboards to using Grafana over graphite-api with backend Blueflood (away from Grafana over graphite-web and Carbon).

We saw that nonNegativeDerivative() function behaves differently on graphite-web and graphite-api

For example, observe the 2 images:
Graphite-web
![screen shot 2015-06-04 at 3 54 47 pm](https://cloud.githubusercontent.com/assets/8238570/7996121/0ca1fa20-0ad2-11e5-8e04-16cc824617fa.png)

Graphite-api
![Graphite-api](https://cloud.githubusercontent.com/assets/8238570/7996094/c8f5ce00-0ad1-11e5-81fe-c8ebc6eeb755.png)

Have you come across this phenomenon? 

After getting rid of nonNegativeDerivative the graphs are identical:

Graphite-web
![screen shot 2015-06-04 at 3 56 39 pm](https://cloud.githubusercontent.com/assets/8238570/7996152/53bca55e-0ad2-11e5-89b7-d0eb069b2156.png)

Graphite-api
![screen shot 2015-06-04 at 3 56 29 pm](https://cloud.githubusercontent.com/assets/8238570/7996155/55c02772-0ad2-11e5-978b-df54a4979225.png)

Any thoughts?

**Comment by tilogaat** [comment]
After getting rid of nonNegativeDerivative the graphs are identical:

Graphite-web
![screen shot 2015-06-04 at 3 56 39 pm](https://cloud.githubusercontent.com/assets/8238570/7996152/53bca55e-0ad2-11e5-89b7-d0eb069b2156.png)

Graphite-api
![screen shot 2015-06-04 at 3 56 29 pm](https://cloud.githubusercontent.com/assets/8238570/7996155/55c02772-0ad2-11e5-978b-df54a4979225.png)

**Comment by goru97** [comment]
I've posted this issue here as well:
https://answers.launchpad.net/graphite/+question/268039

May be we can get some help from graphite-web community.

**Comment by brutasse** [comment]
@tilogaat did you find the cause of the issue?
