### ISSUE TITLE
Add support for creating events (like in graphite-web)

### ISSUE THREAD

**Issue by alexgear** [brutasse/graphite-api#117]
Lack of this feature is really pushing me out of using graphite-api.

**Comment by brutasse** [comment]
There's currently no persistence layer apart from time series interaction in graphite-api, and storing events would require a database of some sort. I'm not overly enthusiastic about the idea of requiring an additional database to run graphite-api…

If you use grafana, it supports events (called annotations) via graphite targets or elasticsearch / influxdb.

If you're using another dashboard, you can send your events to carbon's storage and use `drawAsInifinte()` to get a similar result.

Is that something you can consider?

**Comment by alexgear** [comment]
I am using grafana and I've tried this method, but I can't get as rich information as from graphite events, like custom descriptions.

Is it possible to enable some optional database support?

**Comment by brutasse** [comment]
I'm open to contributions but I'm not going to work on this myself… Feel free to reopen as a pull request :)
