### ISSUE TITLE
Search index file is always 0 bytes

### ISSUE THREAD

**Issue by nikut** [brutasse/graphite-api#131]
Not sure if there is something I'm missing here, but graphite-api's search index file is always 0 bytes. If I remove it and call http://localhost:8888/index I get a connection close after whatever gunicorn's timeout is set to (currently 120 seconds) and the index file has reappeared (so graphite-api is definitely able to write to it), but is again 0 bytes.

How is this supposed to work? Should I just keep increasing gunicorn's timeout? It looks like graphite-api stops responding to any other requests as long as the index request is running, so that does not seem like a good idea. Is there another way to trigger index creation/update? Is it failing for some other reason? Does it even matter? Would having a search index speed things up?

I'm running graphite-api 1.1 now but had the same issue on 1.0.1. Here's the related part of my graphite-api.yaml:

```
search_index: /logs/graphite/storage/index
finders:
  - graphite_api.finders.whisper.WhisperFinder
functions:
  - graphite_api.functions.SeriesFunctions
  - graphite_api.functions.PieFunctions
whisper:
  directories:
    - /logs/graphite/storage/whisper
```
Thanks!

**Comment by brutasse** [comment]
The only API endpoint that uses the index is `/metrics/index.json` so if you or your dashboard(s) don't use that, it's not useful to create the index.

How many metrics do you have? A large number of metrics would be the only reason for timeouts on index generation.

You can always update it by hand, in a python shell:

```
$ python
>>> from graphite_api.app import build_index
>>> build_index()
```

How long does the `build_index()` call take?

**Comment by nikut** [comment]
Ah, thanks for the explanation! I'm using Grafana which does not use that endpoint as far as I know, so I guess it does not matter. 

I tried it anyway and build_index() took close to 5 minutes. I do have a fair amount of metrics (over 100k) and my storage may not quite be up to the task currently. Considering that, the graphite-api + Grafana combination works amazingly well and is generally quite responsive.

Thanks again for your help!

**Comment by brutasse** [comment]
Cool! Indeed, no need for the index with grafana :)
