### ISSUE TITLE
Clarify "No Pickle"

### ISSUE THREAD

**Issue by JFC-MC** [brutasse/graphite-api#136]
Hello,

Could you please clarify the phrase "No Pickle" (as it stated in the README).
There are two "pickles" I know:
1. protocol for writing metrics with Carbon.
2. serialized Python object.
The first one used by Carbon only and have no sense to graphite-api, so you meant the "serialized Python object", am I right?

Please reflect it in the README.md to avoid possible confusions for other people too.
(there are too many entities/terms linked with graphite, so it's better to encourage clarity in documentation)
Thanks!

**Comment by brutasse** [comment]
Hi @JFC-MC -- you're correct that Pickle refers to rendering. But note that the Pickle carbon protocol is also "serialized Python objects" :) They're the same [Python pickle](https://docs.python.org/3.5/library/pickle.html).
