### ISSUE TITLE
graphite-api 1.1.1 hitting out of memory

### ISSUE THREAD

**Issue by ibuclaw** [brutasse/graphite-api#141]
Have hit the same problem twice in one day after upgrading to version 1.1.1 with #119 applied (upgraded from version 1.1 with #119 unapplied)

(Using gunicorn) it looks like the worker threads for the API spiral out of control until it hits OOM.

As this doesn't appear to be a deterministic thing, I'll have a look to see if it is instead triggered by rendering a certain graph.

![mem_usage](https://cloud.githubusercontent.com/assets/397929/10851983/775e0608-7f2e-11e5-9af3-fe21ff734e6e.png)

**Comment by ibuclaw** [comment]
Left it running over the weekend and nothing happened.  Which makes it seem more likely that it was caused by a specific call into graphite-api.  Have got logging working now, so will wait and see if anything is captured from that.

**Comment by brutasse** [comment]
OK, let me know if you find something…

**Comment by ibuclaw** [comment]
A month has passed and this has not recurred in production.  I'll close for now but will watch out when updating to any next releases.
