### ISSUE TITLE
Does graphite-api run on Windows?

### ISSUE THREAD

**Issue by JFC-MC** [brutasse/graphite-api#148]
Hello

Does graphite-api have a Windows platform support?

**Comment by brutasse** [comment]
Hi,

Python supports the Windows platform and I don't think anything prevents Graphite-api from running on Windows. That said, setting up an environment with the compiled dependencies (cairo / cairocffi) might be a bit painful. Also I don't have the capacity to support windows, I only run Linux machines.

Let me know if you find windows-specific issues.
