### ISSUE TITLE
proper error logging in the docker image

### ISSUE THREAD

**Issue by Dieterbe** [brutasse/graphite-api#16]
While testing my custom finder, I can make gunicorn return "500 Internal Server Error"  by doing requests to  `/render` and `/metrics/find`

i use the image as per https://index.docker.io/u/brutasse/graphite-api/,
and hence run `gunicorn -b 0.0.0.0:8000 -w 2 --log-level debug graphite_api.app:app`
but it only logs https://gist.github.com/Dieterbe/10199015 i don't get anything more.
nothing on the terminal, no logfiles :(
i want to see why it errors, if there's any python errors and stack dumps, etc.

**Comment by brutasse** [comment]
Done in https://github.com/brutasse/graphite-api/commit/b7571feecc6bb9a5e0f3ae31503b9ee585b98c31, at last :)
