### ISSUE TITLE
Add custom config path to setup.cfg

### ISSUE THREAD

**Issue by JFC-MC** [brutasse/graphite-api#163]
Hello!

Thanks again for graphite-api, it's amazing )

In some cases(when user has no root privileges or graphite-api should be installed in custom directory, such as /home/user/graphite-api or /srv/app/myapp) it would be very useful to specify CONFIG_PATH at the moment of installation with pip. E.g. (like we do it with other parameters that can be redefined):
`pip install carbon --install-option="--prefix=/home/user/graphite-api" `
Yes, I know about another approach.
> If you need the Graphite-API config file to be stored in another place than /etc/graphite-api.yaml, you can set a custom location using the GRAPHITE_API_CONFIG environment variable:
> export GRAPHITE_API_CONFIG=/var/lib/graphite/config.yaml

But if it'd be available with 
`pip install carbon --install-option="--config_path=/any/path` it would be very convenient. 
Please add such an option to setup.cfg/setup.py.

Thanks in advance!

**Comment by brutasse** [comment]
Hello! I'm not a fan of setting these options at install time… You'd end up with a behavior different from what's documented which could be confusing. Is there anything that prevents you from using `GRAPHITE_API_CONFIG`? I'd like to keep things as simple as possible.
