### ISSUE TITLE
Debian 9: systemd unit file typo

### ISSUE THREAD

**Issue by mattayes** [brutasse/graphite-api#240]
Hi folks:

The current `systemd` unit file has a typo: `RequireMountsFor` should be [`RequiresMountsFor`](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#RequiresMountsFor=):

# Current

\# /lib/systemd/system/graphite-api.service
[Unit]
Description=Graphite-API service
Requires=graphite-api.socket
RequireMountsFor=/var/log/graphite-api /var/lib/graphite/whisper /var/lib/graphite-api
ConditionFileIsExecutable=/usr/bin/gunicorn3
ConditionPathExists=/etc/graphite-api.yaml
ConditionPathExists=/usr/lib/python3/dist-packages/graphite_api/app.py

[Service]
ExecStart=/usr/bin/gunicorn3 --name=graphite-api graphite_api.app:app
Restart=on-failure
User=_graphite
Group=_graphite
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s TERM $MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target

# Change
[Unit]
...
RequiresMountsFor=...
...

Let me know if you need any more details!

**Comment by vincentbernat** [comment]
Thanks for the report. I'll fix that for Debian Sid but it's unlikely a fix will be pushed to Debian Stretch. If you rely on this directive, you'll have to override it in `/etc/systemd/system/graphite-api.service.d/require.conf`.

**Comment by brutasse** [comment]
Thanks @vincentbernat and @mattayes! I'll close this issue here. :+1:

**Comment by mattayes** [comment]
@vincentbernat thanks for the advice! Question: Why won't a fix be pushed to Stretch?

**Comment by vincentbernat** [comment]
Only security issues can be pushed directly to a stable release. However, we could push a fix as an errata for a "point release". However, this is intended only for important or critical bugs. Does the bug affect you for anything else than a cosmetic warning?

**Comment by mattayes** [comment]
@vincentbernat Would prefer to not have unnecessary warnings and have the correct settings by default if at all possible.
