### ISSUE TITLE
Do not exclude tests in release

### ISSUE THREAD

**Issue by offlinehacker** [brutasse/graphite-api#27]
Is there any speciffic reason why do you exclude tests on pypi releases? We are in favour of running automated tests, before putting our packages in production, and also have setup that does so.

**Comment by filippog** [comment]
FWIW I think it'd be nice to have tests shipped on pypi, also files in `MANIFEST.in` affects only source distribution, not the `bdist` setuptools targets or even `install` since `tests` isn't inside the package.

```
graphite-api-1.0.1$ cat MANIFEST.in 
include README.rst LICENSE
graphite-api-1.0.1$ virtualenv /tmp/ga-venv
...
graphite-api-1.0.1$ /tmp/ga-venv/bin/python setup.py install
...
graphite-api-1.0.1$ find /tmp/ga-venv/lib/python2.7/site-packages/graphite_api-1.0.1-py2.7.egg/ | grep tests
graphite-api-1.0.1$
```
