### ISSUE TITLE
astimezone() cannot be applied to a naive datetime

### ISSUE THREAD

**Issue by llange** [brutasse/graphite-api#51]
Hello,

Using master, I encounter the following error:
```
  ...
  File "/usr/share/graphite-api/.venv27/lib/python2.7/site-packages/graphite_api/app.py", line 469, in evaluateTokens
    return fetchData(requestContext, tokens.pathExpression)
  File "/usr/share/graphite-api/.venv27/lib/python2.7/site-packages/graphite_api/render/datalib.py", line 86, in fetchData
    startTime = int(epoch(requestContext['startTime']))
  File "/usr/share/graphite-api/.venv27/lib/python2.7/site-packages/graphite_api/utils.py", line 91, in epoch
    return calendar.timegm(dt.astimezone(pytz.utc).timetuple())
ValueError: astimezone() cannot be applied to a naive datetime"
```

In fact, sometimes the `dt` variable has no timezone : 
```
dt: datetime.datetime(2014, 8, 27, 14, 11, 46, 425395, tzinfo=<StaticTzInfo 'Universal'>)
dt: datetime.datetime(2014, 7, 28, 0, 0)
```

I did not have the time to search where does it come from, and instead I added this "last-chance" quick and dirty fix, that I don't like as it hardcodes the TZ (even if, as I'm guessing, it seems to occur from dates without times, and thus we could consider that the caller is referring to UTC TZ.). It may have, to be correct, to use the configured TZ in the config file ; however I'd prefer to find the source of the TZ-less datetime.

```
diff --git a/graphite_api/utils.py b/graphite_api/utils.py
index 156d628..8284183 100644
--- a/graphite_api/utils.py
+++ b/graphite_api/utils.py
@@ -84,4 +84,6 @@ def epoch(dt):
     """
     Returns the epoch timestamp of a timezone-aware datetime object.
     """
+    if dt.tzinfo is None:
+        dt = dt.replace(tzinfo=pytz.utc)
     return calendar.timegm(dt.astimezone(pytz.utc).timetuple())
```

**Comment by loisaidasam** [comment]
Just encountered this on branch `0.9.x` - any updates?

**Comment by checkmypi** [comment]
+1

**Comment by winguru** [comment]
@checkmypi @loisaidasam @llange This issue should be fixed in the latest master now.

Can you please test and confirm if this is working for you now?

**Comment by brutasse** [comment]
Closing -- feel free to reopen if you are still seeing issues.

**Comment by brutasse** [comment]
And thanks @winguru!
