### ISSUE TITLE
Handling multiple targets is far from beeing optimal

### ISSUE THREAD

**Issue by Civil** [brutasse/graphite-api#53]
Some backends have fetch_multi support, but it's not utilized when there are several targets in URL. That causes very slow performance for some backends (like influxdb, which has quite big penalty for each select, and for example for 10 targets there'll be 20 queries - 10 lists and 10 selects).

While digging to that issue, I've also found that current grammar.parseString is a bit messy (not well documented, hard to understand why it's generating such consturctions).

As example, I've dumped results from a simple query: https://gist.github.com/Civil/c35293bc318e28ab07d1

I think this is bloated (and have lots of duplicating data) and can be reduced a lot. Also if parser is rewritten, it'll be possible to implement multi_fetch for data in more cleaner way

**Comment by brutasse** [comment]
#119 fixes this
