### ISSUE TITLE
500 errors on /metrics/find?query=*

### ISSUE THREAD

**Issue by voxter** [brutasse/graphite-api#58]
Hi there,

I recently attempted an upgrade from InfluxDB 0.6.4 to 0.8.1 (In between I have also tried 0.6.5, 0.7.0 as well)

After upgrading, I had a problem with influxdb snapshots for some reason, which caused me to delete my raft directory and have it rebuild one.  I also re created the database and the database user - however, once this was all done, any query to /metrics/find?query=* returned a 500 error.  Doing a query for some specific data (which did return correctly using the InfluxDB browser) simply returned "[ ]"

Is there anything I can do to debug this to figure out why that's happening, aside from just seeing the 500 error?

Any known issues with more recent versions of InfluxDB?

Thanks!

**Comment by brutasse** [comment]
Closing since it's been a while and I don't have much influxdb knowledge. Feel free to reopen with more info / stacktraces (current master is more helpful when debugging)
