### ISSUE TITLE
incorrect rendering area mode

### ISSUE THREAD

**Issue by freeseacher** [brutasse/graphite-api#59]
hi!
in my opinion rendering in areamode=all is incorrect. 
if one area is under another it is drwaed by line only. but perfect mode is like rrdgrapg do. i ought to see one area under another one
like this one. 
![graph_image php](https://cloud.githubusercontent.com/assets/289277/4260331/83bfdd8c-3b36-11e4-920e-77bbdc258fad.png)

as i can see filling mode is default cairo.OPERATOR_OVER. that will do exactly what i thing is right begavior http://cairographics.org/operators/

![OPERATOR_OVER](http://cairographics.org/operators/over.png)

but in some case drawing is still wrong
![graphite](https://cloud.githubusercontent.com/assets/289277/4260346/b46675d0-3b37-11e4-8618-f778c8e59c9e.png)

**Comment by brutasse** [comment]
This has been fixed, closing.
