### ISSUE TITLE
ValueError: divideSeries second argument must reference exactly 1 series

### ISSUE THREAD

**Issue by Dieterbe** [brutasse/graphite-api#66]
upon `target=divideSeries(sumSeries(stats.*.memcached_stats_archive_read), sumSeries(stats.*.memcached_stats_archive_get))`
i'm getting:
```
graphite_api.functions in divideSeries

ValueError: divideSeries second argument must reference exactly 1 series
```

this is triggered by
```
 def divideSeries(requestContext, dividendSeriesList, divisorSeriesList):
      if len(divisorSeriesList) != 1:
          raise ValueError(
              "divideSeries second argument must reference exactly 1 series")
```
however, the following works:
```
target=sumSeries(stats.*.memcached_stats_archive_read)&target=sumSeries(stats.*.memcached_stats_archive_get)
```
but it says "No Data"

so it looks like somehow the `len(divisorSeriesList)` breaks when divisorSeriesList is 1 series, but not containing any data, or something

**Comment by brutasse** [comment]
Could you show me some test data that triggers the issue? In JSON format for example… It'd help reproduce the problem in a regression test.

**Comment by brutasse** [comment]
I'm unable to reproduce with current graphite-api. `divideSeries` on two `sumSeries` works fine… Please reopen if the issue persists on your setup!
