### ISSUE TITLE
"single stage" query execution?

### ISSUE THREAD

**Issue by Dieterbe** [brutasse/graphite-api#78]
right now, for a given query, we always first look up which metrics match (i.e. by querying the storage), then generate a query expression, and hit the storage again with the query.

in the case of for example InfluxDB we could make this more efficient: there's no need to do two steps , we could convert the input query directly into a data query the storage understands and the storage will resolve automatically the series it needs to incorporate.

it would be nice if we could somehow make this workflow work in graphite-api, because it can make requests return quicker.

**Comment by brutasse** [comment]
Fixed in #119!
