### ISSUE TITLE
No handler & target matching

### ISSUE THREAD

**Issue by vgoldshteyn** [brutasse/graphite-api#81]
Hi,

I have setup the graphite-api + cyanite  + grafana.
It seems to run fine and I can get the metrics.

I see 2 issues:
1)
I do get 'No handlers could be found for logger "flask.app"' error when I try to query with the target containing a value list...i.e. {p1,p2}.*
 wget -qO- "http://xxxx/render?target={srv1,srv2}.cpuload.avg1&from=-5min&until=now&format=json&maxDataPoints=960"

2) 
when I run below query...I get results for 2 metrics srv1.cpuload.avg1 & srv1.cpuload.avg15
my expectation is only to get the data for srv1.cpuload.avg1

wget -qO- "http://xxxx/render?target=srv1.cpuload.avg1&from=-5min&until=now&format=json&maxDataPoints=960"

thanks for your help

**Comment by chjohnst** [comment]
CentOS or RHEL?  I have seen issues on CentOS6 here with a zope-interface package getting in the way of things before.

**Comment by brutasse** [comment]
This problem is most likely fixed in cyanite itself. The issue where a query for "srv1.cpuload.avg1" also returns "srv1.cpuload.avg15" is cause by cyanite's index, which has changed recently. Closing, feel free to reopen if the problem persists with cyanite master.
