### ISSUE TITLE
Having issues installing graphite-api oncentos 6.5

### ISSUE THREAD

**Issue by shaimona** [brutasse/graphite-api#90]
I have followed the instructions at http://graphite-api.readthedocs.org/en/latest/deployment.html#apache-mod-wsgi. I am seeing the processes running. However I'm getting this error when trying to access data "The requested URL /render was not found on this server." . Also I don't see logs I specified in yaml file. Since there is no log file I am not sure what is failing where.  Is there any other instruction for centos I can follow?

**Comment by brutasse** [comment]
Sorry for the late response. There must be some logs from your web server at least. If you're seeing a 404 it's probably a misconfiguration of Apache itself. The wsgi app might not even be running, hence the absence of log file. Can you increase verbosity in Apache and look at the HTTP logs?

**Comment by brutasse** [comment]
Closing this as it's been inactive for a while. Feel free to reopen with more information!
