### ISSUE TITLE
500 errors on targets with "/" in them

### ISSUE THREAD

**Issue by fire** [brutasse/graphite-api#97]
I'm using the influxdb proxy and grafana complains about targets with "/" in them. I had to replace them with "*" in my queries.

**Comment by brutasse** [comment]
There isn't much I can do in graphite-api about that… Either it's an issue for the graphite influxdb plugin or for grafana. In the graphite ecosystem it's also very common to avoid "special" characters and only use `[a-z0-9_-]+` as metric names and dots as directory separators.
