### ISSUE TITLE
areaMode=stacked is broken (doesn't show individual targets)

### ISSUE THREAD

**Issue by Dieterbe** [brutasse/graphite-api#99]
request is basically just `target=groupByNode(stats.*.foo.*.*,3,'sumSeries')` and `target=groupByNode(stats.*.foo.*.*,3,'sumSeries')&areaMode=stacked`

current code:
![render](https://cloud.githubusercontent.com/assets/20774/6621899/9e544d52-c8af-11e4-851c-6779ecdd15a8.png)
![render-stacked-broken](https://cloud.githubusercontent.com/assets/20774/6621976/11f2d0f8-c8b0-11e4-8c05-0acd4b748f21.png)
it seems like #62 is the culprint.
when i change it back to fill() it works as expected:
![render-areamode-broken](https://cloud.githubusercontent.com/assets/20774/6621900/9e54528e-c8af-11e4-927f-616dacf97e27.png)

note, while testing add some `extra=shizzle` http params to the url otherwise browser might cache the png's.

**Comment by iain-buclaw-sociomantic** [comment]
I saw this too and ended up reverting #59 locally.
